/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.c
**     Project   : Lab_3
**     Processor : MC9S12C32MFA25
**     Component : MC9S12C32_48
**     Version   : Component 02.001, Driver 02.06, CPU db: 2.87.402
**     Datasheet : MC9S12C128 Rev 01.23 05/2007
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 3/5/2013, 8:19 PM
**     Abstract  :
**         This component "MC9S12C32_48" implements properties, methods,
**         and events of the CPU.
**     Settings  :
**
**     Contents  :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**         Delay100US  - void Cpu_Delay100US(word us100);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Cpu. */

#include "LCD_EN.h"
#include "LCD_RS.h"
#include "MotorR_Drive.h"
#include "MotorR_Enable.h"
#include "MotorL_Drive1.h"
#include "MotorL_Drive2.h"
#include "MotorL_Drive3.h"
#include "MotorL_Drive4.h"
#include "MotorL_Enable1.h"
#include "MotorL_Enable2.h"
#include "Motor1_Timer2.h"
#include "Motor2_Timer2.h"
#include "AD1.h"
#include "TI1.h"
#include "TI2.h"
#include "Err.h"
#include "Events.h"
#include "Cpu.h"

#define CGM_DELAY  0x0BFFU

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR reegister */

/*Definition of global shadow variables*/
byte Shadow_E;
byte Shadow_A;
byte Shadow_M;
byte Shadow_T;

#pragma CODE_SEG __NEAR_SEG NON_BANKED


/*
** ===================================================================
**     Method      :  Cpu_Cpu_Interrupt (component MC9S12C32_48)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Cpu_Interrupt)
{
  /*lint -save -e950 Disable MISRA rule (1.1) checking. */
  asm(BGND);
  /*lint -restore Enable MISRA rule (1.1) checking. */
}


/*
** ===================================================================
**     Method      :  Cpu_Delay100US (component MC9S12C32_48)
**
**     Description :
**         This method realizes software delay. The length of delay
**         is at least 100 microsecond multiply input parameter
**         [us100]. As the delay implementation is not based on real
**         clock, the delay time may be increased by interrupt
**         service routines processed during the delay. The method
**         is independent on selected speed mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         us100           - Number of 100 us delay repetitions.
**                         - The value of zero results in maximal 
**                           delay of approx. 6.5 seconds.
**     Returns     : Nothing
** ===================================================================
*/
#pragma NO_ENTRY                       /* Suppress generation of entry code in a function */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
#pragma MESSAGE DISABLE C5703          /*Disable C5703: Parameter ‘<Parameter>’ declared in function ‘<Function>’ but not referenced */
void Cpu_Delay100US(word us100)
{
  /* irremovable overhead (ignored): 13 cycles */
  /* ldd:  2 cycles overhead (load parameter into register) */
  /* jsr:  4 cycles overhead (call this function) */
  /* rts:  7 cycles overhead (return from this function) */

  /* irremovable overhead for each 100us cycle (counted): 13 cycles */
  /* dbne:  3 cycles overhead (return from this function) */

  /*lint -save  -e950 -e522 Disable MISRA rule (1.1,14.2) checking. */
  asm {
    loop:
    /* 100 us delay block begin */
    /*
     * Delay
     *   - requested                  : 100 us @ 24MHz,
     *   - possible                   : 2400 c, 100000 ns
     *   - without removable overhead : 2397 c, 99875 ns
     */
    pshd                               /* (2 c: 83.33 ns) backup D */
    ldd #$031C                         /* (2 c: 83.33 ns) number of iterations */
    label0:
    dbne d, label0                     /* (3 c: 125 ns) repeat 796x */
    puld                               /* (3 c: 125 ns) restore D */
    nop                                /* (1 c: 41.67 ns) wait for 1 c */
    nop                                /* (1 c: 41.67 ns) wait for 1 c */
    /* 100 us delay block end */
    dbne d, loop                       /* us100 parameter is passed via D register */
    rts                                /* return from subroutine */
  };
  /*lint -restore Enable MISRA rule (1.1,14.2) checking. */
}

#pragma CODE_SEG DEFAULT

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S12C32_48)
**
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S12C32_48)
**
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (component MC9S12C32_48)
**
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (component MC9S12C32_48)
**
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from Wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC9S12C32_48)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */
#pragma CODE_SEG __NEAR_SEG NON_BANKED

#define INITRG_ADR  0x11U              /* Register map position register */

#pragma NO_FRAME                       /* Suppress generation of frame code */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
void _EntryPoint(void)
{
  /* ### MC9S12C32_48 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* Initialization of the registers INITRG, INITRM, INITEE is done to protect them to be written accidentally later by the application */
  /*lint -save  -e950 -e923 Disable MISRA rule (1.1,11.3) checking. */
  *(byte*)INITRG_ADR = 0x00U;          /* Set the register map position */
  asm("nop");                          /* nop instruction */
  /*lint -restore Enable MISRA rule (1.1,11.3) checking. */
  /* INITRM: RAM15=0,RAM14=0,RAM13=1,RAM12=1,RAM11=1,??=0,??=0,RAMHAL=1 */
  setReg8(INITRM, 0x39U);              /* Set the RAM map position */ 
  /* MISC: ??=0,??=0,??=0,??=0,EXSTR1=1,EXSTR0=1,ROMHM=0,ROMON=1 */
  setReg8(MISC, 0x0DU);                 
  /* PEAR: NOACCE=0,??=0,??=0,NECLK=1,??=0,??=0,??=0,??=0 */
  setReg8(PEAR, 0x10U);                 
  /*  System clock initialization */
  /* CLKSEL: PLLSEL=0,PSTP=0,SYSWAI=0,ROAWAI=0,PLLWAI=0,CWAI=0,RTIWAI=0,COPWAI=0 */
  setReg8(CLKSEL, 0x00U);              /* Select clock source from XTAL and set bits in CLKSEL reg. */ 
  /* PLLCTL: CME=1,PLLON=0,AUTO=1,ACQ=1,??=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0xB1U);              /* Disable the PLL */ 
  /* SYNR: ??=0,??=0,SYN5=0,SYN4=0,SYN3=0,SYN2=0,SYN1=1,SYN0=0 */
  setReg8(SYNR, 0x02U);                /* Set the multiplier register */ 
  /* REFDV: ??=0,??=0,??=0,??=0,REFDV3=0,REFDV2=0,REFDV1=0,REFDV0=0 */
  setReg8(REFDV, 0x00U);               /* Set the divider register */ 
  /* PLLCTL: CME=1,PLLON=1,AUTO=1,ACQ=1,??=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0xF1U);               
  while(CRGFLG_LOCK == 0U) {           /* Wait until the PLL is within the desired tolerance of the target frequency */
  }
  /* CLKSEL: PLLSEL=1 */
  setReg8Bits(CLKSEL, 0x80U);          /* Select clock source from PLL */ 
  /*** End of PE initialization code after reset ***/
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  __asm("jmp _Startup");               /* Jump to C startup code */
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

#pragma CODE_SEG DEFAULT
/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S12C32_48)
**
**     Description :
**         Initializes components and provides common register 
**         initialization. The method is called automatically as a part 
**         of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* Common initialization of the CPU registers */
  /* PEAR: NOACCE=0,NECLK=1 */
  clrSetReg8Bits(PEAR, 0x80U, 0x10U);   
  /* PORTE: BIT7=0,BIT4=0 */
  clrReg8Bits(PORTE, 0x90U);            
  /* PUCR: PUPEE=0,PUPAE=0 */
  clrReg8Bits(PUCR, 0x11U);             
  /* DDRE: BIT7=1,??=1,??=1,BIT4=1,??=1,??=1 */
  setReg8Bits(DDRE, 0xFCU);             
  /* PORTA: BIT0=0 */
  clrReg8Bits(PORTA, 0x01U);            
  /* DDRA: ??=1,??=1,??=1,??=1,??=1,??=1,??=1,BIT0=1 */
  setReg8(DDRA, 0xFFU);                 
  /* PTM: PTM5=0,PTM4=0,PTM3=0,PTM2=0,PTM1=0,PTM0=0 */
  clrReg8Bits(PTM, 0x3FU);              
  /* WOMM: WOMM5=0,WOMM4=0,WOMM3=0,WOMM2=0,WOMM1=0,WOMM0=0 */
  clrReg8Bits(WOMM, 0x3FU);             
  /* PERM: PERM5=0,PERM4=0,PERM3=0,PERM2=0,PERM1=0,PERM0=0 */
  clrReg8Bits(PERM, 0x3FU);             
  /* DDRM: DDRM5=1,DDRM4=1,DDRM3=1,DDRM2=1,DDRM1=1,DDRM0=1 */
  setReg8Bits(DDRM, 0x3FU);             
  /* PTT: PTT5=0,PTT4=0,PTT1=0,PTT0=0 */
  clrReg8Bits(PTT, 0x33U);              
  /* PERT: PERT5=0,PERT4=0,PERT1=0,PERT0=0 */
  clrReg8Bits(PERT, 0x33U);             
  /* DDRT: DDRT5=1,DDRT4=1,DDRT1=1,DDRT0=1 */
  setReg8Bits(DDRT, 0x33U);             
  /* TSCR1: TEN=0,TSWAI=0,TSFRZ=0,TFFCA=0 */
  clrReg8Bits(TSCR1, 0xF0U);            
  /* PACTL: CLK1=0,CLK0=0 */
  clrReg8Bits(PACTL, 0x0CU);            
  /* OC7M: OC7M4=0,OC7M3=0,OC7M2=0,OC7M1=0,OC7M0=0 */
  clrReg8Bits(OC7M, 0x1FU);             
  /* TIOS: IOS4=1,IOS3=1,IOS2=1,IOS1=1,IOS0=1 */
  setReg8Bits(TIOS, 0x1FU);             
  /* TCTL2: OM3=0,OL3=0,OM2=0,OL2=0,OM1=0,OL1=0,OM0=0,OL0=0 */
  setReg8(TCTL2, 0x00U);                
  /* TTOV: TOV4=0,TOV3=0,TOV2=0,TOV1=0,TOV0=0 */
  clrReg8Bits(TTOV, 0x1FU);             
  /* TSCR2: TCRE=0,PR2=1,PR1=0,PR0=1 */
  clrSetReg8Bits(TSCR2, 0x0AU, 0x05U);  
  /* TFLG1: C7F=1,C6F=1,C5F=1,C4F=1,C3F=1,C2F=1,C1F=1,C0F=1 */
  setReg8(TFLG1, 0xFFU);                
  /* TCTL1: OM4=0,OL4=0 */
  clrReg8Bits(TCTL1, 0x03U);            
  /* TIE: C4I=1,C3I=1,C2I=1,C1I=1,C0I=1 */
  setReg8Bits(TIE, 0x1FU);              
  /* ATDDIEN: IEN2=0,IEN1=0,IEN0=0 */
  clrReg8Bits(ATDDIEN, 0x07U);          
  /* CRGINT: LOCKIE=0,SCMIE=0 */
  clrReg8Bits(CRGINT, 0x12U);           
  /* VREGCTRL: LVIE=0 */
  clrReg8Bits(VREGCTRL, 0x02U);         
  /* COPCTL: WCOP=0,RSBCK=0,??=0,??=0,??=0,CR2=0,CR1=0,CR0=0 */
  setReg8(COPCTL, 0x00U);               
  /* RDRIV: RDPE=0,RDPB=0,RDPA=0 */
  clrReg8Bits(RDRIV, 0x13U);            
  /* RDRAD: RDRAD7=0,RDRAD6=0,RDRAD5=0,RDRAD4=0,RDRAD3=0,RDRAD2=0,RDRAD1=0,RDRAD0=0 */
  setReg8(RDRAD, 0x00U);                
  /* RDRM: RDRM5=0,RDRM4=0,RDRM3=0,RDRM2=0,RDRM1=0,RDRM0=0 */
  clrReg8Bits(RDRM, 0x3FU);             
  /* RDRP: RDRP5=0 */
  clrReg8Bits(RDRP, 0x20U);             
  /* RDRS: RDRS1=0,RDRS0=0 */
  clrReg8Bits(RDRS, 0x03U);             
  /* RDRT: RDRT7=0,RDRT6=0,RDRT5=0,RDRT4=0,RDRT3=0,RDRT2=0,RDRT1=0,RDRT0=0 */
  setReg8(RDRT, 0x00U);                 
  /* INTCR: IRQEN=0 */
  clrReg8Bits(INTCR, 0x40U);            
  /* PERP: ??=1,??=1,??=1,??=1,??=1,??=1,??=1 */
  setReg8Bits(PERP, 0xDFU);             
  /* DDRB: ??=1,??=1,??=1,??=1,??=1,??=1,??=1 */
  setReg8Bits(DDRB, 0xEFU);             
  /* PERS: ??=1,??=1 */
  setReg8Bits(PERS, 0x0CU);             
  /* PERJ: PERJ7=1,PERJ6=1 */
  setReg8Bits(PERJ, 0xC0U);             
  /* ### MC9S12C32_48 "Cpu" init code ... */
  /* ### BitIO "LCD_EN" init code ... */
  Shadow_E &= 0x7FU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "LCD_RS" init code ... */
  Shadow_A = (byte)0x00U;              /* Initialize pin shadow variable bit */
  /* ### BitsIO "MotorR_Drive" init code ... */
  Shadow_M &= 0xC3U;                   /* Initialize port shadow variable */
  /* ### BitIO "MotorR_Enable" init code ... */
  Shadow_E &= 0xEFU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "MotorL_Drive1" init code ... */
  Shadow_M &= 0xFEU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "MotorL_Drive2" init code ... */
  Shadow_M &= 0xFDU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "MotorL_Drive3" init code ... */
  Shadow_T &= 0xEFU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "MotorL_Drive4" init code ... */
  Shadow_T &= 0xDFU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "MotorL_Enable1" init code ... */
  Shadow_T &= 0xFEU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "MotorL_Enable2" init code ... */
  Shadow_T &= 0xFDU;                   /* Initialize pin shadow variable bit */
  /* ### TimerInt "Motor1_Timer2" init code ... */
  /* TC0: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=1,BIT6=0,BIT5=0,BIT4=1,BIT3=0,BIT2=1,BIT1=1,BIT0=0 */
  setReg16(TC0, 0x96U);                /* Store given value to the compare register */ 
  /* ### TimerInt "Motor2_Timer2" init code ... */
  /* TC1: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=1,BIT6=0,BIT5=0,BIT4=1,BIT3=0,BIT2=1,BIT1=1,BIT0=0 */
  setReg16(TC1, 0x96U);                /* Store given value to the compare register */ 
  /* ###  "AD1" init code ... */
  AD1_Init();
  /* ### TimerInt "TI1" init code ... */
  TI1_Init();
  /* ### TimerInt "TI2" init code ... */
  TI2_Init();
  /* ### TimerInt "Err" init code ... */
  /* TC4: BIT15=1,BIT14=0,BIT13=1,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=1,BIT7=0,BIT6=0,BIT5=1,BIT4=0,BIT3=0,BIT2=0,BIT1=1,BIT0=0 */
  setReg16(TC4, 0xA122U);              /* Store given value to the compare register */ 
  /* Common peripheral initialization - ENABLE */
  /* TSCR1: TEN=1 */
  setReg8Bits(TSCR1, 0x80U);            
  __EI();                              /* Enable interrupts */
}

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */

/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
