/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : MotorR_Drive.c
**     Project   : Lab_3
**     Processor : MC9S12C32MFA25
**     Component : BitsIO
**     Version   : Component 02.102, Driver 03.14, CPU db: 2.87.402
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2/19/2013, 7:13 PM
**     Abstract  :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**     Settings  :
**         Port name                   : M
**
**         Bit mask of the port        : $003C
**         Number of bits/pins         : 4
**         Single bit numbers          : 0 to 3
**         Values range                : 0 to 15
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PTM       [$0250]
**         Port control register       : DDRM      [$0252]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    43   |   PM2_MISO
**                    1      |    42   |   PM3_SS
**                    2      |    41   |   PM4_MOSI
**                    3      |    40   |   PM5_SCK
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents  :
**         GetDir - bool MotorR_Drive_GetDir(void);
**         SetDir - void MotorR_Drive_SetDir(bool Dir);
**         GetVal - byte MotorR_Drive_GetVal(void);
**         PutVal - void MotorR_Drive_PutVal(byte Val);
**         GetBit - bool MotorR_Drive_GetBit(byte Bit);
**         PutBit - void MotorR_Drive_PutBit(byte Bit, bool Val);
**         SetBit - void MotorR_Drive_SetBit(byte Bit);
**         ClrBit - void MotorR_Drive_ClrBit(byte Bit);
**         NegBit - void MotorR_Drive_NegBit(byte Bit);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE MotorR_Drive. */

#include "MotorR_Drive.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG MotorR_Drive_DATA     /* Select data segment "MotorR_Drive_DATA" */
#pragma CODE_SEG MotorR_Drive_CODE
#pragma CONST_SEG MotorR_Drive_CONST   /* Constant section for this module */
/*
** ===================================================================
**     Method      :  MotorR_Drive_GetMsk (component BitsIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const byte MotorR_Drive_Table[4U] = { /* Table of mask constants */
   0x04U, 0x08U, 0x10U, 0x20U
};

static byte MotorR_Drive_GetMsk (byte PinIndex)
{
  return (byte)((PinIndex<4U) ? MotorR_Drive_Table[PinIndex] : 0U); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  MotorR_Drive_GetVal (component BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 15)
** ===================================================================
*/
byte MotorR_Drive_GetVal(void)
{
  return (byte)((getReg8(PTM) & 0x3CU) >> 2U); /* Return port data */
}

/*
** ===================================================================
**     Method      :  MotorR_Drive_PutVal (component BitsIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pins
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 15)
**     Returns     : Nothing
** ===================================================================
*/
void MotorR_Drive_PutVal(byte Val)
{
  Val = (byte)((Val & 0x0FU) << 2U);   /* Mask and shift output value */
  Shadow_M = (byte)((Shadow_M & 0xC3U) | Val); /* Set-up shadow variable */
  setReg8(PTM, (getReg8(PTM) & (byte)(~(byte)0x3CU)) | Val); /* Put masked value on port */
}

/*
** ===================================================================
**     Method      :  MotorR_Drive_GetBit (component BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 3)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool MotorR_Drive_GetBit(byte Bit)
{
  byte const Mask = MotorR_Drive_GetMsk(Bit); /* Temporary variable - bit mask to test */
  return (bool)(((getReg8(PTM) & Mask) == Mask)? 1U: 0U); /* Test if specified bit of port register is set */
}

/*
** ===================================================================
**     Method      :  MotorR_Drive_PutBit (component BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**           a) direction = Input  : sets the value of the specified
**                                   bit; this operation will be
**                                   shown on output after the
**                                   direction has been switched to
**                                   output (SetDir(TRUE);)
**           b) direction = Output : directly writes the value of the
**                                   bit to the appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 3)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void MotorR_Drive_PutBit(byte Bit, bool Val)
{
  byte const Mask = MotorR_Drive_GetMsk(Bit); /* Temporary variable - put bit mask */
  if (Val) {
    setReg8Bits(PTM, Mask);            /* [bit (Bit+2)]=0x01U */
    Shadow_M |= Mask;                  /* Set appropriate bit in shadow variable */
  } else { /* !Val */
    clrReg8Bits(PTM, Mask);            /* [bit (Bit+2)]=0x00U */
    Shadow_M &= (byte)~(byte)Mask;     /* Clear appropriate bit in shadow variable */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  MotorR_Drive_ClrBit (component BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**           a) direction = Input  : sets the specified bit to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   beenswitched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
void MotorR_Drive_ClrBit(byte Bit)
{
  byte const Mask = MotorR_Drive_GetMsk(Bit); /* Temporary variable - set bit mask */
  clrReg8Bits(PTM, Mask);              /* [bit (Bit+2)]=0x00U */
  Shadow_M &= (byte)~(byte)Mask;       /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  MotorR_Drive_SetBit (component BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**           a) direction = Input  : sets the specified bit to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
void MotorR_Drive_SetBit(byte Bit)
{
  byte const Mask = MotorR_Drive_GetMsk(Bit); /* Temporary variable - set bit mask */
  setReg8Bits(PTM, Mask);              /* [bit (Bit+2)]=0x01U */
  Shadow_M |= Mask;                    /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  MotorR_Drive_NegBit (component BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**           a) direction = Input  : inverts the specified bit;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly inverts the value
**                                   of the appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void MotorR_Drive_NegBit(byte Bit)
{
  byte const Mask = MotorR_Drive_GetMsk(Bit); /* Temporary variable - set bit mask */
  invertReg8Bits(PTM, Mask);           /* [bit (Bit+2)]=invert */
  Shadow_M ^= Mask;                    /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  MotorR_Drive_GetDir (component BitsIO)
**
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
/*
bool MotorR_Drive_GetDir(void)

**  This method is implemented as a macro. See MotorR_Drive.h file.  **
*/

/*
** ===================================================================
**     Method      :  MotorR_Drive_SetDir (component BitsIO)
**
**     Description :
**         This method sets direction of the component.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void MotorR_Drive_SetDir(bool Dir)
{
  if (Dir) {
    setReg8(PTM, (getReg8(PTM) & (byte)(~(byte)0x3CU)) | (Shadow_M & 0x3CU)); /* Put masked value on port */
    /* DDRM: DDRM5=1,DDRM4=1,DDRM3=1,DDRM2=1 */
    setReg8Bits(DDRM, 0x3CU);           
  } else { /* !Dir */
    /* DDRM: DDRM5=0,DDRM4=0,DDRM3=0,DDRM2=0 */
    clrReg8Bits(DDRM, 0x3CU);           
  } /* !Dir */
}


/* END MotorR_Drive. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
