/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : MotorR_Enable.c
**     Project   : Lab_3
**     Processor : MC9S12C32MFA25
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.15, CPU db: 2.87.402
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2/19/2013, 7:13 PM
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       14            |  PE4_ECLK
**             ----------------------------------------------------
**
**         Port name                   : E
**
**         Bit number (in port)        : 4
**         Bit mask of the port        : $0010
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PORTE     [$0008]
**         Port control register       : DDRE      [$0009]
**         Port function register      : INTCR     [$001E]
**
**         Optimization for            : speed
**     Contents  :
**         SetDir - void MotorR_Enable_SetDir(bool Dir);
**         GetVal - bool MotorR_Enable_GetVal(void);
**         PutVal - void MotorR_Enable_PutVal(bool Val);
**         ClrVal - void MotorR_Enable_ClrVal(void);
**         SetVal - void MotorR_Enable_SetVal(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE MotorR_Enable. */

#include "MotorR_Enable.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG MotorR_Enable_DATA    /* Select data segment "MotorR_Enable_DATA" */
#pragma CODE_SEG MotorR_Enable_CODE
#pragma CONST_SEG MotorR_Enable_CONST  /* Constant section for this module */
/*
** ===================================================================
**     Method      :  MotorR_Enable_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool MotorR_Enable_GetVal(void)

**  This method is implemented as a macro. See MotorR_Enable.h file.  **
*/

/*
** ===================================================================
**     Method      :  MotorR_Enable_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void MotorR_Enable_PutVal(bool Val)
{
  if (Val) {
    setReg8Bits(PORTE, 0x10U);         /* BIT4=0x01U */
    Shadow_E |= 0x10U;                 /* Set-up shadow variable */
  } else { /* !Val */
    clrReg8Bits(PORTE, 0x10U);         /* BIT4=0x00U */
    Shadow_E &= 0xEFU;                 /* Set-up shadow variable */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  MotorR_Enable_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**           a) direction = Input  : sets the output value to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void MotorR_Enable_ClrVal(void)

**  This method is implemented as a macro. See MotorR_Enable.h file.  **
*/

/*
** ===================================================================
**     Method      :  MotorR_Enable_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**           a) direction = Input  : sets the output value to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void MotorR_Enable_SetVal(void)

**  This method is implemented as a macro. See MotorR_Enable.h file.  **
*/

/*
** ===================================================================
**     Method      :  MotorR_Enable_SetDir (component BitIO)
**
**     Description :
**         This method sets direction of the component.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void MotorR_Enable_SetDir(bool Dir)
{
  if (Dir) {
    setReg8(PORTE, (getReg8(PORTE) & (byte)(~(byte)0x10U)) | (Shadow_E & 0x10U)); /* BIT4=Shadow_E[bit 4] */
    setReg8Bits(DDRE, 0x10U);          /* BIT4=0x01U */
  } else { /* !Dir */
    clrReg8Bits(DDRE, 0x10U);          /* BIT4=0x00U */
  } /* !Dir */
}


/* END MotorR_Enable. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
